### ISSUE TITLE
Incorrect folder name(course title)

### ISSUE THREAD

**Issue by chenjau** [r0oth3x49/lynda-dl#33]
os: macos 10.12.6
py: python 3.6
lynda-dl: master

course url: https://www.lynda.com/3ds-Max-tutorials/3ds-Max-2013-Essential-Training/95341-2.html
expect: 3ds Max 2013 Essential Training
result:  ds Max E3 Essential Training

course url: https://www.lynda.com/Architecture-tutorials/Michelle-Kaufmanns-Platinum-LEED-Home-Remodel-Start-Finish/95254-2.html
expect: Michelle Kaufmanns Platinum LEED Home Remodel Start to Finish
result:   Michelle Kaufmanns Platinum LEED Home Remodel_ Start to Finish

& feature request: some courses has same name(with different year or topic), make sure folder(course) name unique, so we can avoid download them to same folder.

thank you for your hard work.

**Comment by r0oth3x49** [comment]
@chenjau thanks for the report but this is actually a default behavior rather than an error. i 'm skipping the starting numbering and assigning my own lecture / chapter numbering. also skipping some disallowed characters although those are specific to windows but to keep the naming convention same for each platform i 'm skipping those characters.
