### ISSUE TITLE
[feature request] read links from file

### ISSUE THREAD

**Issue by hereisderek** [r0oth3x49/lynda-dl#61]
thanks so much for this awesome tool! 

I'm currently using a bash script for downloading multiple links, it works but I'm worried if I keep logging in and off lynda might find me specious and block my ip/account.

it'd be better if it can directly read links from a specified file, and perhaps share login session across downloads. 

I've also noticed getting info can take some time, so potentially it can also retrieve other downloads' info while downloading.

**Comment by r0oth3x49** [comment]
@hereisderek its already there you can either provide a link of course or a file containing links of courses separated by new line.

getting info takes time because there is no direct API call which gives all the info against a course that's why it parse one by one each lecture for info extracting. 

if you can explain a bit more what you actually want me to implement that will be great.
