### ISSUE TITLE
Stuck in progress

### ISSUE THREAD

**Issue by cdslxc** [r0oth3x49/lynda-dl#81]
![image](https://user-images.githubusercontent.com/8092790/83738435-8410b900-a67e-11ea-9167-4d1d9128f123.png)

This course has more than these.
Help.
https://www.linkedin.com/learning/learning-incopy/

**Comment by codencoffe** [comment]
1. I had this issue consistently when i was using username and password.
2. Now I am using cookies text file and having this issue sometime only due to cookies expiry, Network issue (multiple users downloading same time). 
3. This is painful, when you start downloading a multiple course overnight and in the morning you discover it stuck on first course only. 

Developer, please suggest a work around or add an option to skip on error.

**Comment by r0oth3x49** [comment]
@codencoffe i have started working on updating all the repo, soon will update this one too and release new version.

**Comment by r0oth3x49** [comment]
@imtiendat i don't provide any exe file for this repository so if you are using some sort of exe use it on your own risk, i 'm not responsible for anything. you should use this repository using python.
